apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-wkld
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/criscola/capi-gce-demo-argocd
    targetRevision: HEAD
    path: clusterapi
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
